<?php
return [
    'categories.view'=> 'categories View',
    'categories.create'=> 'categories create',
    'categories.edit'=> 'categories edit',
    'categories.delete'=> 'categories delete',
    'categories.restore'=> 'categories restore',
    'categories.trash'=> 'categories trash',
    'products.view'=> 'products View',
    'products.create'=> 'products create',
    'products.edit'=> 'products edit',
    'products.delete'=> 'products delete',
    'orders.view'=> 'orders View',
    'orders.create'=> 'orders create',
    'orders.edit'=> 'orders edit',
    'orders.delete'=> 'orders delete',
    'users.view'=> 'users View',
    'users.create'=> 'users create',
    'users.edit'=> 'users edit',
    'users.delete'=> 'users delete',
    'roles.view'=> 'roles View',
    'roles.create'=> 'roles create',
    'roles.edit'=> 'roles edit',
    'roles.delete'=> 'roles delete',
    'permissions.view'=> 'permissions View',
    'permissions.create'=> 'permissions create',
    'permissions.edit'=> 'permissions edit',
    'permissions.delete'=> 'permissions delete',
];